<?php
if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group(array(
    'key' => 'group_5cd9b1db4925d',
    'title' => 'Fighter Settings',
    'fields' => array(
      array(
        'key' => 'field_5cdc766c6e9db',
        'label' => 'Fighter Visibility',
        'name' => 'tbp_fighter_visibility',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5f32da2297235',
        'label' => 'Related Fighters Image',
        'name' => 'tbp_related_fighters_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'full',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5cd9c875ddf96',
        'label' => 'Fighter Boxrec ID',
        'name' => 'tbp_fighter_boxrec_id',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5cd9b1dcd5331',
        'label' => 'Featured Photo Settings',
        'name' => 'tbp_f_featured_photo_settings',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5cd1f65cd5bed',
            'label' => 'Photo Credit',
            'name' => 'tbp_f_featured_photo_credit',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd1f6b9d5bee',
            'label' => 'Photo Description',
            'name' => 'tbp_f_featured_photo_description',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5cd9b2c9a1895',
        'label' => 'Fighter Profile Data',
        'name' => 'tbp_fighter_profile_datas',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5cd9b33a8479c',
            'label' => 'Fighter Nickname',
            'name' => 'tbp_fighter_profile_nickname',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9b35a8479d',
            'label' => 'Fighter Birth Date',
            'name' => 'tbp_fighter_profile_birthdate',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'display_format' => 'F j, Y',
            'return_format' => 'F j, Y',
            'first_day' => 1,
          ),
          array(
            'key' => 'field_5cd9b7928479e',
            'label' => 'Fighter Birth Place',
            'name' => 'tbp_fighter_profile_birthplace',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9b8178479f',
            'label' => 'Fighter Division',
            'name' => 'tbp_fighter_profile_division',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'Bantamweight' => 'Bantamweight',
              'Cruiserweight' => 'Cruiserweight',
              'Featherweight' => 'Featherweight',
              'Flyweight' => 'Flyweight',
              'Heavyweight' => 'Heavyweight',
              'Jr Bantamweight' => 'Jr Bantamweight',
              'Jr Featherweight' => 'Jr Featherweight',
              'Jr Heavyweight' => 'Jr Heavyweight',
              'Jr Lightweight' => 'Jr Lightweight',
              'Jr Middleweight' => 'Jr Middleweight',
              'Jr Welterweight' => 'Jr Welterweight',
              'Junior Flyweight' => 'Junior Flyweight',
              'Light Flyweight' => 'Light Flyweight',
              'Light Heavyweight' => 'Light Heavyweight',
              'Lightweight' => 'Lightweight',
              'Middleweight' => 'Middleweight',
              'Mini Flyweight' => 'Mini Flyweight',
              'Minimumweight' => 'Minimumweight',
              'Super Bantamweight' => 'Super Bantamweight',
              'Super Featherweight' => 'Super Featherweight',
              'Super Flyweight' => 'Super Flyweight',
              'Super Lightweight' => 'Super Lightweight',
              'Super Middleweight' => 'Super Middleweight',
              'Super Welterweight' => 'Super Welterweight',
              'Welterweight' => 'Welterweight',
            ),
            'default_value' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 1,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ce5a94b4eeb8',
            'label' => 'Fighter Stance',
            'name' => 'tbp_fighter_profile_stance',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9c1e0847a0',
            'label' => 'Fighter Height',
            'name' => 'tbp_fighter_profile_height',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ce5a9604eeb9',
            'label' => 'Fighter Reach',
            'name' => 'tbp_fighter_profile_reach',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5cd9b1dcd57af',
        'label' => 'Fighter Excerpt',
        'name' => 'tbp_fighter_excerpt',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 6,
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_5cd9b1dcd5b91',
        'label' => 'Fighter Gallery',
        'name' => 'tbp_fighter_gallery',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Add Photo',
        'sub_fields' => array(
          array(
            'key' => 'field_5cd9b1e0038dc',
            'label' => 'Photo',
            'name' => 'tbp_fighter_gallery_photo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5cd9b1e003d39',
            'label' => 'Credit',
            'name' => 'tbp_fighter_gallery_credit',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9b1e0040a0',
            'label' => 'Description',
            'name' => 'tbp_fighter_gallery_description',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5cd9c357ddf91',
        'label' => 'Fighter Records',
        'name' => 'tbp_fighter_records',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5cd9c6f3ddf92',
            'label' => 'Date',
            'name' => 'tbp_fighter_records_date',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'display_format' => 'Y-m-d',
            'return_format' => 'Y-m-d',
            'first_day' => 1,
          ),
          array(
            'key' => 'field_5cd9c80fddf93',
            'label' => 'Opponent',
            'name' => 'tbp_fighter_records_opponent',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ce5d2e5cd9db',
            'label' => 'Opponent Record',
            'name' => 'tbp_fighter_records_opponent_record',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9c82bddf94',
            'label' => 'Location',
            'name' => 'tbp_fighter_records_location',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cd9c83bddf95',
            'label' => 'Result',
            'name' => 'tbp_fighter_records_result',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'Win' => 'Win',
              'Lost' => 'Lost',
              'Draw' => 'Draw',
              'SC' => 'SC',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'fighter',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'excerpt',
      1 => 'discussion',
      2 => 'revisions',
      3 => 'author',
      4 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

endif;
